### PR TITLE
Prevent empty search

### PR DESCRIPTION
**Pull request by Meisenburger13**
If someone tries to search without typing anything in, there is a little message below the search bar to "Please enter a search term".
I've changed it in the two places, where the search bar is implemented and added a little css to the corresponding files.

Please review and merge.

### CODE REVIEW

**Comment by hannah-sems** [comment]
It works for the 'empty search' (no input given) but no reminder is given for the empty string " " , it just searches for it anyways.

**Comment by Meisenburger13** [comment]
good point, I've fixed that now. Now it also shows the message if someone tries to search for only spaces, no matter how many, so any search string needs to contain at least one proper character

**Review by hannah-sems — APPROVED** [review]
After your latest commit everything works as expected. Think it's ready for merging.

**Review by huntila — APPROVED** [review]
👍

**Pull request merged**
